### ISSUE TITLE
android.view.WindowLeaked: Activity instamojo.library.Instamojo has leaked window DecorView@55b96c8[]

### ISSUE THREAD

**Issue by anjanaps** [Instamojo/instamojo-android-sdk#84]
Please help me if you know how to solve this 

`E/WindowManager: android.view.WindowLeaked: Activity instamojo.library.Instamojo has leaked window DecorView@55b96c8[] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:489)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.app.Dialog.show(Dialog.java:330)
        at instamojo.library.Instamojo.showDialogue(Instamojo.java:260)
        at instamojo.library.Instamojo.createPaymentRequest(Instamojo.java:195)
        at instamojo.library.Instamojo.access$400(Instamojo.java:26)
        at instamojo.library.Instamojo$1.onResponse(Instamojo.java:127)
        at instamojo.library.API.AccessToken$AccessTokenAsyn.onPostExecute(AccessToken.java:46)
        at instamojo.library.API.AccessToken$AccessTokenAsyn.onPostExecute(AccessToken.java:25)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6521)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by amannirala13** [comment]
Seems like you are trying to access a Dialog from the context of an Activity after exiting it. I would need a bit more details on the implementation to understand the issue.
